alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
    ruleNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    retention: 7d
  # Добавляем конфигурацию Service для Prometheus
  service:
    type: ClusterIP
    port: 9090
    targetPort: 9090
    # Дополнительно: если нужно указать аннотации или селекторы
    # annotations: {}
    # labels: {}

defaultRules:
  rules:
    alertmanager: false

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
  initChownData:
    enabled: false

# Если prometheus-adapter поддерживается (обычно нет)
prometheus-adapter:
  enabled: false  # Лучше установить отдельно