# Generated by Django 5.1.4 on 2025-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deletion_on_first_reading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
