# values.yaml

## Глобальные параметры
global:
  redis:
    password: "your-strong-password"
  storageClass: "standard"


architecture: replication

## Аутентификация
auth:
  enabled: true
  password: "your-strong-password" 

## Конфигурация мастера
master:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
    accessModes:
      - ReadWriteOnce
  service:
    type: ClusterIP
    nodePorts:
      redis: ""  


replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
    accessModes:
      - ReadWriteOnce

## Метрики Prometheus
metrics:
  enabled: true
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9121"
  serviceMonitor:
    enabled: true  # Включено для интеграции с kube-prometheus-stack
    interval: 30s
    namespace: monitoring
    additionalLabels:
      release: kube-prometheus-stack
