# Generated by Django 5.0.1 on 2025-06-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='deletion_on_first_reading',
        ),
        migrations.RemoveField(
            model_name='note',
            name='read_count',
        ),
    ]
