# Generated by Django 5.0.1 on 2025-07-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_note_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='burn_after_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_burned',
            field=models.BooleanField(default=False),
        ),
    ]
