apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-app
  labels:
    app: drf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drf-app
  template:
    metadata:
      labels:
        app: drf-app
    spec:
      containers:
      - name: drf-app-container
        image: drf-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: root.postgresql-cluster.credentials.postgresql.acid.zalan.do
              key: username
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: root.postgresql-cluster.credentials.postgresql.acid.zalan.do
              key: password
              optional: false
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: meilisearch-secret
              key: MEILI_MASTER_KEY
              optional: false

      # 🔁 Flask Sidecar
      - name: l2-sidecar
        image: flask-l2-cache:latest
        ports:
        - containerPort: 8500
        env:
        - name: REDIS_URL
          value: "redis://:your-strong-password@my-redis-master.redis.svc.cluster.local:6379/0"
        - name: KEY_BATCH_SIZE
          value: "20"
        - name: L2_MIN_KEYS
          value: "5"
        - name: BUFFER_KEY_SET
          value: "buffer_keys"
        - name: USED_KEY_ZSET
          value: "used_keys"
        - name: FLASK_PORT
          value: "8500"

---
apiVersion: v1
kind: Service
metadata:
  name: drf-app-service
  labels:
    app: drf-app
spec:
  selector:
    app: drf-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 8000