apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
type: Opaque
stringData:
  REDIS_URL: "redis://:your-strong-password@my-redis-master.redis.svc.cluster.local:6379/0"
  REDIS_PASSWORD: "your-strong-password"