apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: drf-app-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: drf-app
    app.kubernetes.io/instance: drf-app
spec:
  selector:
    matchLabels:
      app: drf-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s