# Generated by Django 5.0.1 on 2025-06-30 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_note_deletion_on_first_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.note'),
        ),
    ]
