# Generated by Django 5.0.1 on 2025-07-02 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_note_to_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dead_line',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
    ]
