# Generated by Django 5.1.4 on 2025-01-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Мой пользователь', 'verbose_name_plural': 'Мои пользователи'},
        ),
        migrations.AlterModelOptions(
            name='password_blocker',
            options={'verbose_name': 'Блокировка аккаунта', 'verbose_name_plural': 'Блокировки аккаунтов'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
        migrations.AlterModelTable(
            name='password_blocker',
            table='account_block',
        ),
    ]
