# Generated by Django 5.1.4 on 2025-01-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
