# Generated by Django 5.1.4 on 2025-01-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_accounts', '0003_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
