# Включаем создание Service
service:
  enabled: true
  type: ClusterIP
  port: 7700  # стандартный порт Meilisearch
  targetPort: 7700
  annotations: {}
  labels: {}

persistence:
  enabled: true
  storageClass: standard
  size: 1Gi
  accessMode: ReadWriteOnce